---
url: http://www.greenlab-coworking.com
title: Greenlab Coworking - Espace de coworking en Province de Luxembourg
subtitle: A blogging framework for hackers.
author: Greenlab Coworking
simple_search: false
description: 
date_format: "%d/%m/%Y"
subscribe_rss: "/atom.xml"
subscribe_email: 
email: 
root: "/"
permalink: "/blog/:year/:month/:day/:title/"
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
rdiscount:
  extensions:
  - autolink
  - footnotes
  - smart
highlighter: pygments
paginate: 10
paginate_path: blog/posts/:num
recent_posts: 5
excerpt_link: Lire la suite &rarr;
excerpt_separator: "<!--more-->"
titlecase: false
default_asides:
- custom/asides/latest-blog-posts.html
- custom/asides/free-trial.html
- custom/asides/newsletter-form.html
github_user: 
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true
twitter_user: greenlabcowork
twitter_tweet_button: false
google_plus_one: false
google_plus_one_size: medium
googleplus_user: "+Greenlab-coworking"
googleplus_hidden: true
pinboard_user: 
pinboard_count: 3
delicious_user: 
delicious_count: 3
disqus_short_name: 
disqus_show_comment_count: false
google_analytics_tracking_id: UA-46630064-1
facebook_like: false
navigation:
- text: Accueil
  url: "/"
- text: Tarifs
  url: "/tarifs/"
  layout: page
- text: Frontaliers
  url: "/frontaliers/"
  layout: page
- text: Blog
  url: "/blog/"
- text: Nos partenaires
  url: "/nos-partenaires/"
- text: Nous contacter
  url: "/nous-contacter/"
category_title_prefix: 'Catégorie : '
timezone: Europe/Brussels
